### ISSUE TITLE
Should measureMemory work on iframes?

### ISSUE THREAD

**Issue by npm1** [WICG/performance-measure-memory#16]
I'm curious what you think about calling performance.measureMemory() from an iframe to get the full page memory - it seems unsafe from a security perspective. Should this API just work on top-level browsing contexts or are there use-cases for calling this on iframes?

**Comment by ulan** [comment]
The API is available only in the same-origin iframes:
https://wicg.github.io/performance-measure-memory/#memory-measurement-allowed-predicate

Calling the API in a cross-origin iframe would throw an exception.
